# Corona algorithm parameters for position reconstruction. Included by other configs.
corona_params   = dict(
  Qthr          =  5 * pes,   # Minimum SiPM charge threshold
  Qlm           = 40 * pes,   # Charge threshold for local maximum identification
  lm_radius     = 15 * mm ,   # Search radius for local maxima (NEW detector)
  new_lm_radius = 25 * mm ,   # Search radius for local maxima (NEXT-100)
  msipm         =  1          # Minimum number of SiPMs required
)
